### ISSUE TITLE
no endpoint value for healthy volume

### ISSUE THREAD

**Issue by loganhz** [rancher/longhorn-manager#13]
no endpoint value for healthy volume
but it has for detached volume

**Comment by yasker** [comment]
That's a bug, it should only show up for volume not in detached or created mode. Will check that.

**Comment by yasker** [comment]
It does show up correctly in the API UI. Can you double check?

**Comment by yasker** [comment]
The endpoint shows in the single volume(GET), but not in the LIST.

Fixed at: https://github.com/rancher/longhorn-manager/commit/f2e0f2a104c6ef105435982c698bb6d955ae95b7
