### ISSUE TITLE
Deleted Volume Can't be attach again

### ISSUE THREAD

**Issue by biblesyme** [rancher/longhorn-manager#14]
Steps:
1.   Add a Volume named as 'aaron'
2.   Attach Volume 'aaron' to the host
3.   Delete Volume 'aaron'
4.   Add Volume 'aaron' again
5.   Attach it to the same host.

Result:
   show error:
   "unable to attach volume: failed to start the controller for volume 'aaron': fail to create controller container: Error response from daemon: Conflict. The name \"/aaron-controller\" is already in use by container 409e0d760774681f9d0d51f484ebc2720e92d93ac41cc40bc4d557511716151f. You have to remove (or rename) that container to be able to reuse that name.",
<img width="1440" alt="screen shot 2017-04-06 at 17 50 32" src="https://cloud.githubusercontent.com/assets/9334435/24748484/5f815560-1af2-11e7-8a3c-954a82b7b126.png">

**Comment by yasker** [comment]
Seems cleanup work got wrong. Will check it.

**Comment by yasker** [comment]
Should be fixed.
