### ISSUE TITLE
No integration test case for recurring snapshot retaining feature

### ISSUE THREAD

**Issue by yasker** [rancher/longhorn-manager#23]
Need to add it.

**Comment by imikushin** [comment]
It's in there: `test_recurring_snapshot_live_update_retain`

**Comment by yasker** [comment]
I see. I thought it's not there because it doesn't execute the purge and I fixed it in https://github.com/rancher/longhorn-manager/commit/6246540a54571a11f4ea413c578f52248aaaf5fd . Seems the test case only check if the snapshot is in `removed` state, rather than really get it removed.

It needs an update to make sure that there are snapshots removed from the disk. We may need to do a periodic purge in the future, but now it's done after every cleanup in recurring snapshot.

**Comment by imikushin** [comment]
I've added the check for the purge. The test checks that purge has been issued and as a result some of the "removed" containers are actually gone.

**Comment by yasker** [comment]
Fixed by #24.
